config/routes.rb
Webblog::Application.routes.draw do
  devise_for :users
  resources :blogs do
    resources :comments
    member do
      put 'like', to: 'blogs#upvote'
      post 'love', to: 'blogs#love'
    end
    
  end
  get '/old_blogs', to: 'blogs#old_blogs'

  resources :home, only: [:index]

  get 'tags/:tag', to: 'blogs#index', as: :tag
  get '/photos', to: 'pages#photos'
  get '/videos', to: 'pages#videos'

  post '/tinymce_assets' => 'tinymce_assets#create'

  root :to => "blogs#index"

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	acts_as_votable
	has_many :comments, dependent: :destroy
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100#" }, default_url: ""

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	acts_as_taggable # Alias for acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :file
  	validates_attachment_content_type :file, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :upvote]


  # GET /blogs
  # GET /blogs.json
  def index
    # require 'json'
    if params[:tag]
      @blogs = Blog.all.tagged_with(params[:tag]).paginate(:page => params[:page]).per_page(20).order('created_at DESC')
    else
      @blogs = Blog.paginate(:page => params[:page]).per_page(20).order('created_at DESC')
      @docs = Nokogiri::XML(File.open("app/assets/javascripts/danika_blog.xml"))
      @images = Nokogiri::XML(File.open("app/assets/javascripts/danika_blog_images.xml"))

      @image = @images.css("item")
      @title = @docs.xpath("//item")
    end

  end

  def old_blogs
      @docs = Nokogiri::XML(File.open("app/assets/javascripts/danika_blog.xml"))
      @images = Nokogiri::XML(File.open("app/assets/javascripts/danika_blog_images.xml"))

      @image = @images.css("item")
      @title = @docs.xpath("//item")
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  def upvote
    @blog
    redirect_to :back
  end

  def love
    @blog = Blog.find(params[:id])

    @blog.increment(:likes)

    @blog.update(likes: @blog.likes)

    render json: @blog.likes
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :image, :tag_list)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.create(params[:comment].permit(:name, :body))

		redirect_to blog_path(@blog)
	end

	def destroy
		@blog = Blog.find(params[:blog_id])
		@comment = @blog.comments.find(params[:id])
		@comment.destroy

		redirect_to blog_path(@blog)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def photos
# 		require "instagram"
# 		# @images = Dir.glob("app/assets/images/*.jpg")

# 		Instagram.configure do |config|
# 		  config.client_id = "95738e94f2fa46dfb4162a09117fd732"
# 		  config.client_secret = "37d21f6d443142b9970b47c096116479"
# 		  # For secured endpoints only
# 		  #config.client_ips = '<Comma separated list of IPs>'
# 		end
# 8a58f043eec64123ba36473f469e72c3
# 		@instagram = Instagram.user_recent_media("3021131281")
	end

	def videos
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tinymce_assets_controller.rb
class TinymceAssetsController < ApplicationController
  respond_to :json

  def create
    geometry = Paperclip::Geometry.from_file params[:file]
    image    = Image.create params.permit(:file, :alt, :hint)

    render json: {
      image: {
        url:    image.file.url,
        height: geometry.height.to_i,
        width:  geometry.width.to_i
      }
    }, layout: false, content_type: "text/html"
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController\

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog, html: { multipart: true } do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="title-field">
    <%= f.text_field :title %>
  </div>
  
  <div class="title-field">
    <%= f.file_field :image %>
  </div>



  <div class="field">
    <%= f.text_area :content, id: 'tinymce4', :class => "tinymce", rel: "tinymce", :rows => 40, :cols => 70 %>
  </div>

  <div class="tags">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit %>
    <button type="button" class="btn btn-primary">Delete</button>
  </div>

<% end %>

app/views/blogs/_side_bar.html.erb
<div class="col-md-4 side_bar">

<div class="side-bar-section">


  <form class="navbar-form" role="search">
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Search">
    </div>
    <button type="submit" class="btn btn-default">Search</button>
  </form>
</div>

  <%= link_to new_blog_path do %>
    <button type="button" class="btn btn-primary">New Blog</button>
  <% end %>

<div class="side-bar-section" style="text-align: center;">
  <h3>About The Author</h3>

  <%= image_tag 'about-the-author.jpg', class: 'about-the-author' %>

  I'm still working on it. Learning more and more about myself each day. After every victory, trial and defeat. Finding out who I am in The Lord... Really realizing that I wasn't created to be a part of this world.

This is me.... A Work in Progress.

DanikaKayelle XOXO

<div class="social-icons">
<%= image_tag 'youtube.png', class: '' %>
<%= image_tag 'facebook.png', class: '' %>
<%= image_tag 'instagram.png', class: '' %>
  
</div>


</div>

<div class="side-bar-section">

  <h3>Recent Post</h3>
    <ul>
      <li>
        <a href="#">This is my new post #1</a>
        <a href="#">This is my new post #2</a>
        <a href="#">This is my new post #3</a>
        <a href="#">This is my new post #4</a>
        <a href="#">This is my new post #5</a>
      </li>
    </ul>

</div>

<div class="side-bar-section">
  <h3>Latest Instagram</h3>
    <%= image_tag 'latest-instagram.jpg', class: 'about-the-author' %>

</div>

<div class="side-bar-section">

    <div id="tag_cloud">
  <h3>Tags</h3>

<% tag_cloud Blog.tag_counts, %w[s m l] do |tag, css_class| %>
  <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>
</div>

</div>

app/views/blogs/edit.html.erb
<%= form_for @blog, html: { multipart: true } do |f| %>

<div class="edit-wrap">
<h1>Edit Post</h1>


  <% if @blog.static_image.present? %>
    <%= image_tag @blog.static_image, class: 'static-image' %>
  <% else %>
    <%= image_tag @blog.image.url(:medium) %>
  <% end %>


  
  <div class="title-field">
    <%= f.file_field :image %>
  </div>

  <div class="title-field">
    <%= f.text_field :title %>
  </div>

  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




  <div class="field">
    <%= f.text_area :content, id: 'tinymce4', :class => "tinymce", rel: "tinymce", :rows => 40, :cols => 70 %>
  </div>

  <div class="tags">
    <%= f.label :tag_list, "Tags (separated by commas)", class: 'tags_header' %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-primary' %>
    <button type="button" class="btn btn-primary">Delete</button>
  </div>

<% end %>



<div class="show-buttons">
  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

</div>

app/views/blogs/index.html.erb
  <div class="scroll-container">
    <div class="wrap">


     

      <div class="frame" id="basic" style="overflow: hidden;" data-count="<%= @blogs.count %>">
        <ul class="clearfix" style="transform: translateZ(0px) translateX(-684px); width: 6840px;">

        <% @blogs.each do |blog| %>

          <li>

            <div class="posts-wrap col-md-12 clearfix">

                  <% if blog.static_image.present? %>
                    <div class="col-xs-12 image-container">
                      <%= link_to blog  do %>
                        <%= image_tag blog.static_image, class: 'post-image', style: 'width: 100%' %>
                        <div class="image-overlay">
                          <span class="share-icon"><i class="fa fa-instagram" aria-hidden="true"></i></span>
                             <span class="share-icon"><i class="fa fa-twitter" aria-hidden="true"></i></span>
                             <span class="share-icon"><i class="fa fa-facebook-official" aria-hidden="true"></i></span>
                          </span>
                        </div>
                      <% end %> 
                    </div>
                  <% elsif blog.static_image == "" && blog.image.url(:large) == ""  %>

                  <% else %> 
                    <div class="col-xs-12 image-container">
                      <%= link_to blog  do %>
                        <%= image_tag blog.image.url(:large), class: 'post-image', style: 'width: 100%' %>
                        <div class="image-overlay">
                          <span class="share-icon"><i class="fa fa-instagram" aria-hidden="true"></i></span>
                             <span class="share-icon"><i class="fa fa-twitter" aria-hidden="true"></i></span>
                             <span class="share-icon"><i class="fa fa-facebook-official" aria-hidden="true"></i></span>
                          </span>
                        </div>
                      <% end %> 
                    </div>
                  <% end %> 


              <div class="col-xs-12">
                <div class="col-xs-12" style="text-align: center;">
                <%= link_to blog  do %>
                  <h3 class="blog-title"><%= blog.title %></h3>
                  <% end %> 
                </div>
                  <% @content = truncate_html(blog.content.html_safe, length: 250) %>
                  <div class="col-xs-12 blog-content" style="padding: 0;"><%=  strip_tags( @content) %></div>


              </div>

                <div class="col-xs-12 read-more-container" >
                  <% if user_signed_in? %>
                  <%= user_session %>
                    <%= link_to edit_blog_path(blog)  do %>
                      <p class="read-more">Edit</p>
                    <% end %>
                  <% else %>
                    <%= link_to blog  do %>
                      <p class="read-more">Read More...</p>
                    <% end %>
                  <% end %>

                  

                  <p class="tags" style="display:none;">
                    <%= blog.created_at.strftime("%B %d, %Y ")%>
                    /by <%= User.last.first_name%><%= User.last.last_name%>
                    /Tags: in <%= raw blog.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')%>
                  </p>

                </div>

           
              </div>

          </li>
      <% end %>

        </ul>

        
      </div>

      <div class="controls center hidden-xs">

        <span class="prev btn direction-button"><i class="fa fa-chevron-left" aria-hidden="true"></i>PREV</span>
        <span class="next btn direction-button">NEXT <i class="fa fa-chevron-right" aria-hidden="true"></i></span>

      <div class="col-xs-12">
        <ul class="pages"><li class="">1</li><li class="active">2</li><li>3</li><li>4</li><li>5</li><li>6</li></ul>
      </div>

      </div>


     <!--  <div class="controls center">
        <span class="btn prev"><i class="fa fa-chevron-left" aria-hidden="true"></i>PREV</span>
        <button class="btn prevPage"><i class="icon-chevron-left"></i><i class="icon-chevron-left"></i> page</button>
        <button class="btn backward"><i class="icon-chevron-left"></i> move</button>

        <div class="btn-group">
          <button class="btn toStart">toStart</button>
          <button class="btn toCenter">toCenter</button>
          <button class="btn toEnd">toEnd</button>
        </div>


        <button class="btn forward">move <i class="icon-chevron-right"></i></button>
        <button class="btn nextPage">page <i class="icon-chevron-right"></i><i class="icon-chevron-right"></i></button>
        <span class="btn next">NEXT <i class="fa fa-chevron-right" aria-hidden="true"></i></span>
      </div> -->
    </div>

      <div class="paginate_container" style="display: none;">
    <%= will_paginate @blogs %>
  </div>

  </div>


<% if false %>

<div class="scroll-container" data-behavior="scroll-container">
<div class="col-md-8 posts-container" data-count="<%= @blogs.count %>">

  <div class="ajax-posts">

<% if true %>
  <% @blogs.each do |blog| %>

    <div class="posts-wrap col-md-4 clearfix">

          <% if blog.static_image.present? %>
            <div class="col-xs-12 image-container">
              <%= link_to blog  do %>
                <%= image_tag blog.static_image, class: 'post-image' %>
              <% end %> 
            </div>
          <% elsif blog.static_image == "" && blog.image.url(:large) == ""  %>

          <% else %> 
            <div class="col-xs-12">
              <%= link_to blog  do %>
                <%= image_tag blog.image.url(:large), class: 'post-image' %>
              <% end %> 
            </div>
          <% end %> 


      <div class="col-sm-12">
        <div class="col-sm-12" style="text-align: center;">
        <%= link_to blog  do %>
          <h3 class="blog-title"><%= blog.title %></h3>
          <% end %> 
        </div>
          <% @content = truncate_html(blog.content.html_safe, length: 300) %>
          <div class="col-xs-12" style="padding: 0;"><%=  strip_tags( @content) %></div>


      </div>

    <% if user_signed_in? or true%>
        <div class="col-xs-12" style="text-align: right;">

        <% if user_signed_in? %>
          <%= link_to blog  do %>
            <p class="read-more">Edit</p>
          <% end %>
        <% else %>
          <%= link_to blog  do %>
            <p class="read-more">Read More...</p>
          <% end %>
        <% end %>

          

          <p class="tags" style="display:none;">
            <%= blog.created_at.strftime("%B %d, %Y ")%>
            /by <%= User.last.first_name%><%= User.last.last_name%>
            /Tags: in <%= raw blog.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')%>
          </p>

        <% if false %>

          <div>
            <%= link_to edit_blog_path(blog)  do %>
              <span>Edit </span> |
            <% end %>

            <%= link_to blog, method: :delete, data: { confirm: 'Are you sure?' }  do %>
              <span> Delete</span>
            <% end %>
          </div>
        <% end %>

        </div>

    <% end %>
      </div>

      
  <% end %>

  </div>


  <div class="paginate_container" style="display: block;">
    <%= will_paginate @blogs %>
  </div>
</div>
</div>

<div class="clearfix"></div>

  <% end %>


  <% end %>  

app/views/blogs/new.html.erb
<div class="edit-wrap">

	<h1>New blog</h1>

	<%= render 'form' %>

	<%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/old_blogs.html.erb
  <div class="posts-wrap clearfix">
    <% imgIDs = @title.css("wp|postmeta wp|meta_key:contains('thumbnail_id') ~ wp|meta_value").try(:text) %>

    <% postId = params[:post_id] %>

    <% if imgIDs != "" %>
      <div class="col-xs-12">
        <%= link_to 'old_blogs'  do %>
          <%= image_tag @image.xpath(".//post_id[text() = '" + imgIDs + "']/following-sibling::attachment_url").text, class: 'post-image' %>
        <% end %> 
      </div>
    <% else %> 
     <div class="col-xs-12">
        <%= link_to 'blog'  do %>
          <%= image_tag '', class: 'post-image', style: 'display: none;' %>
        <% end %> 
      </div>
    <% end %> 

      <div class="col-sm-12">
        <div class="col-sm-12" style="text-align: center;">
          <h3 class="blog-title"><%= @title.xpath("wp:post_id[text() = #{postId} ]/preceding-sibling::title").text %></h3>
          <%= @title.xpath("wp:post_id[text() = #{postId} ]/following-sibling::wp:post_date").text.to_datetime.strftime("%B %d, %Y ") %>
            /by <%= User.last.first_name %><%= User.last.last_name %>
        </div>
        <div class="col-xs-12"><%= @title.xpath("wp:post_id[text() = #{postId} ]/preceding-sibling::content:encoded").text.html_safe %></div>
      </div>

      <hr>
      
      <% if user_signed_in? or false %>
        <div class="col-xs-12">
          <%= link_to 'old_blogs'  do %>
            <button type="button" class="btn btn-primary">Read More</button>
          <% end %>

          <%= link_to 'edit_blog_path(blog)' do %>
            <button type="button" class="btn btn-primary">Edit</button>
          <% end %>

          <%= link_to 'blog', method: :delete, data: { confirm: 'Are you sure?' }  do %>
            <button type="button" class="btn btn-primary">Delete</button>
          <% end %>

          <p class="tags">
            /Tagged With: in 
            <% @title.xpath("wp:post_id[text() = #{postId} ]/following-sibling::category").each do |tag| %>
              <a href=""><%= tag.text %></a>,
            <% end %>
          </p>
          
        </div>

    <% end %>

    <h3>Comments</h3>
		<%= @title.xpath("wp:post_id[text() = #{postId} ]/following-sibling::wp:comment").each do |comment| %>

			<p> <%= comment.xpath("wp:comment_author").text %> </p>
			<p> <%= comment.xpath("wp:comment_date").text.to_datetime.strftime("%B %d, %Y ") %> </p>
			<p> <%= comment.xpath("wp:comment_content").text %> </p>
		<% end %>


  </div>

app/views/blogs/show.html.erb
<div class="show-wrap" data-id="<%= @blog.id %>">
<p id="notice"><%= notice %></p>


	<h3 class="blog-show-title"><%= @blog.title %></h3>



<% if @blog.static_image.present? %>

    <%= image_tag @blog.static_image, class: 'blog-show-image' %>

<% elsif @blog.static_image == "" && @blog.image.url(:medium) == ""  %>

<% else %> 
    <div class="col-xs-12">
        <%= image_tag @blog.image.url(:medium), class: 'blog-show-image' %>
    </div>
<% end %> 

<div class="show-content">
  <%= simple_format(@blog.content.html_safe) %>
</div>
<hr>
	<h4>Tags</h4>
<p class="tags">
	 <%= raw @blog.tag_list.map { |t| link_to t, tag_path(t) }.join(' ')%>
</p>


<%= link_to love_blog_path(@blog), class: "btn btn-default loves" do %>

	<span><i class="fa fa-heart" aria-hidden="true" style="color: red"></i>
		<span data-behavior="likes-counter"> <%= @blog.likes %></span>
	</span>

<% end %> 

<div class="edit-blog">
	<%= link_to 'Edit', edit_blog_path(@blog) %> |
	<%= link_to 'Delete', blog_path(@blog), method: :delete, data: { confirm: 'Are you sure?' } %> |
	<%= link_to 'Back', blogs_path %>
</div>

<hr>


	<div class="comment-form">

		<h2 style="text-align: center;"><%= pluralize(@blog.comments.count, 'Comment') %></h2>
		<%= render @blog.comments %>

		<div class="leave-comment">

			<h3>Leave a Comment:</h3>
			<%= render "comments/form" %>
		</div>
	</div>

</div>

app/views/comments/_comment.html.erb
<div class="comment clearfix">
		<%= image_tag 'https://lh3.googleusercontent.com/-dPlKfVYwEjk/AAAAAAAAAAI/AAAAAAAAAAA/tL2FPdD0TPU/photo.jpg', class: "comment_image col-xs-1" %>
	<div class="comment_content col-xs-11">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>

		<% if user_signed_in? %>
			<p>
				<%= link_to 'Delete', [comment.blog, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %>
			</p>
 		<% end %>

	</div>

</div>
<hr>

app/views/comments/_form.html.erb
<%= form_for([@blog, @blog.comments.build]) do |f| %>
	<p>

		<%= f.text_field :name, placeholder: 'Name' %>
	</p>

	<p>
		<%= f.text_area :body, placeholder: 'Leave a comment' %>
	</p>

	<p>
		<%= f.submit :submit, id: 'submit-comment' %>
	</p>
<% end %>

app/views/home/index.html.erb
<h1>home#index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <title>Webblog</title>
	  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => false %>	 

	
	  <%= csrf_meta_tags %>
	</head>
	<body data-no-turbolink>

		<div class="site-container">
			<div class="notice">
				<%= notice %>
				<%= alert %>
			</div>
			<!-- <p class="alert"></p> -->

			<div class="container">
			<!-- <header></header> -->


			<nav class="navbar navbar-default">
			  <div class="container-fluid" style="padding: 0">


			    <!-- Brand and toggle get grouped for better mobile display -->

			    <% if controller.controller_name == 'blogs' && controller.action_name == 'index' %>
				<div class="scrollbar">
					<div class="handle" style="transform: translateZ(0px) translateX(114px); width: 190px;">
						<div class="mousearea"></div>
					</div>
				</div>
				<% end %>
			    <div class="navbar-header">
			<span class="scroller"></span>

			     <!--  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button> -->
			    </div>

			    <% if controller.controller_name == 'blogs' && controller.action_name == 'show' && false %>
			  <div class="back-blog">
			 	<i class="fa fa-chevron-left" aria-hidden="true"></i>
			 </div>
			 <% end %>

			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class=" " id="bs-example-navbar-collapse-1">
			    	<div class="up-trigger" data-behavior="up-trigger">
			    		<i class="fa fa-chevron-up" aria-hidden="true"></i>
			    	</div>

			      <ul class="nav navbar-nav">

			      <%= content_tag :li do %>
			      	<%= link_to(photos_path)  do %><i class="fa fa-camera" aria-hidden="true"></i><% end %>

			      <% end %>

			      <%= content_tag :li do %>
			      	<%= link_to(blogs_path)  do %><i class="fa fa-th-large" aria-hidden="true"></i><% end %>
			      <% end %> 

			      <%= content_tag :li do %>
			      	<%= link_to(home_index_path)  do %><i class="fa fa-home" aria-hidden="true"></i><% end %>
			      <% end %>

			      <%= content_tag :li do %>
			      	<%= link_to("")  do %><i class="fa fa-shopping-bag" aria-hidden="true"></i><% end %>
			      <% end %>

			      <%= content_tag :li do %>
			      	<%= link_to(videos_path)  do %><i class="fa fa-play" aria-hidden="true"></i><% end %>
			      <% end %>

			       
			      </ul>

			      <div class="nav-bottom">
			      	
				    <% if user_signed_in? %>
				    	<span class="logout-link">
				    		<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
				    	</span>	   

				    <% else %>

				    	

						<% if true %>

					      	<%= form_for(:user, :url => session_path(:user)) do |f| %>
							  <%= f.text_field :email, class: 'login-inputs' %>
							  <%= f.password_field :password, class: 'login-inputs' %>
							  <!-- <%= f.check_box :remember_me %> -->
							  <!-- <%= f.label :remember_me %> -->
							  <%= f.submit 'Sign in', class: 'submit-log-in' %>
							  <%= link_to "Forgot your password?", new_password_path(:user) %>
							<% end %>
						<% end %>

					<% end -%>
			      </div>


			      
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>

				

				<%= yield %>


			</div>

		</div>

 <%= javascript_include_tag "application", "data-turbolinks-track" => true %>


	</body>
</html>

app/views/pages/videos.html.erb
videos page

app/views/videos/index.html.erb
<h1>videos#index</h1>